import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sharebox",
  description: "Generated by team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/parachute-box-solid.svg" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
